{% set name = "pangeo-forge-runner" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pangeo-forge-runner-{{ version }}.tar.gz
  sha256: 1312648494d296c17b97cc4fa623e16df1571cc54b97c8456b2589da40f73df2

build:
  entry_points:
    - pangeo-forge-runner=pangeo_forge_runner.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - importlib-metadata
    - python >=3.9
    - jupyter-repo2docker
    - ruamel.yaml
    - escapism
    - jsonschema
    - traitlets
    - apache-beam ==2.42.0

test:
  imports:
    - pangeo_forge_runner
  commands:
    - pip check
    - pangeo-forge-runner --help
  requires:
    - fsspec
    - pip

about:
  home: https://github.com/pangeo-forge/pangeo-forge-runner
  summary: Commandline tool to manage pangeo-forge feedstocks
  doc_url: https://pangeo-forge-runner.readthedocs.io/
  dev_url: https://github.com/pangeo-forge/pangeo-forge-runner
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - weiji14
