{% set name = "pangeo-forge-runner" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pangeo-forge-runner-{{ version }}.tar.gz
  sha256: 97e016a94ee4e85cf333eb3dbb7a3026ca4bfc67446cf6d4edf1d0f07f79629a

build:
  entry_points:
	@@ -18,15 +18,18 @@ build:

requirements:
  host:
    - python >=3.9  
    - setuptools >=45  
    - setuptools-scm >=6.2  
    - pip  
  run:
    - python >=3.9  
    - jupyter-repo2docker  
    - ruamel.yaml  
    - pangeo-forge-recipes >=0.9.2  
    - escapism  
    - jsonschema  
    - traitlets  

test:
  imports:
	@@ -48,3 +51,4 @@ about:
extra:
  recipe-maintainers:
    - andersy005
    - weiji14
