{% set name = "pangeo-forge-runner" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pangeo-forge-runner-{{ version }}.tar.gz
  sha256: 88e8ffc6bffd3c4f9375fad1914b1c31d8651d872018a669f754a9c6b6bf89e3

build:
  entry_points:
    - pangeo-forge-runner=pangeo_forge_runner.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - jupyter-repo2docker
    - ruamel.yaml
    - pangeo-forge-recipes >=0.9.2
    - traitlets
    - apache-beam ==2.42.0

test:
  imports:
    - pangeo_forge_runner
  commands:
    - pip check
    - pangeo-forge-runner --help
  requires:
    - pip

about:
  home: https://github.com/pangeo-forge/pangeo-forge-runner
  summary: Commandline tool to manage pangeo-forge feedstocks
  doc_url: https://pangeo-forge-runner.readthedocs.io/
  dev_url: https://github.com/pangeo-forge/pangeo-forge-runner
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
