{% set name = "pangeo-forge-runner" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pangeo-forge-runner-{{ version }}.tar.gz
  sha256: e92684f9a32eaebbae1f7db4fb1984737c161072ae1ef6862dea5a05838fcfa6

build:
  entry_points:
    - pangeo-forge-runner=pangeo_forge_runner.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - escapism
    - importlib-metadata
    - jsonschema
    - jupyter-repo2docker
    - python >={{ python_min }}
    - ruamel.yaml
    - traitlets

test:
  imports:
    - pangeo_forge_runner
  commands:
    - pip check
    - pangeo-forge-runner --help
  requires:
    - apache-beam
    - fsspec
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pangeo-forge/pangeo-forge-runner
  summary: Commandline tool to manage pangeo-forge feedstocks
  doc_url: https://pangeo-forge-runner.readthedocs.io/
  dev_url: https://github.com/pangeo-forge/pangeo-forge-runner
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trey-stafford
    - rushirajnenuji
    - mfisher87
    - andersy005
    - weiji14
