{% set name = "pangeo-forge-runner" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pangeo-forge-runner-{{ version }}.tar.gz
  sha256: 78432af5e282f8078366df18750e678a5284ade31ecabbb2ea7013f14761fc7d

build:
  entry_points:
    - pangeo-forge-runner=pangeo_forge_runner.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - fsspec
    - venvception >=0.0.5
    - escapism
    - importlib-metadata
    - jsonschema
    - jupyter-repo2docker
    - python >=3.9
    - ruamel.yaml
    - traitlets

test:
  imports:
    - pangeo_forge_runner
  commands:
    - pip check
    - pangeo-forge-runner --help
  requires:
    - apache-beam
    - fsspec
    - pip

about:
  home: https://github.com/pangeo-forge/pangeo-forge-runner
  summary: Commandline tool to manage pangeo-forge feedstocks
  doc_url: https://pangeo-forge-runner.readthedocs.io/
  dev_url: https://github.com/pangeo-forge/pangeo-forge-runner
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - weiji14
